export default {
  games: [
    { name: 'plinkogo#IOS', value: 'id1525192056#ios' },
    { name: 'plinkogo#安卓', value: 'com.gamemasterf9.plinkogo#android' },
    { name: 'plinkomania#安卓', value: 'com.gamemasterf9.plinkomania#android' },
    { name: 'plinkomania#IOS', value: 'id1525191968#ios' },
    { name: 'pusher#ios', value: 'id1525191759#ios' },
    { name: 'pusher#安卓', value: 'com.gamemasterf9.pushermaster#android' },
    { name: 'arcadepusher#安卓', value: 'com.gamemasterf9.arcadepusher#android' },
    { name: 'arcadepusher#IOS', value: 'id1537729767#ios' },
    { name: 'slotsmaster#安卓', value: 'com.didabu.wildherdslots#android' },
  ],
  categories: [
    { name: '国家', value: 'country_code' },
    { name: '州/县', value: 'state' },
    { name: '媒体渠道', value: 'media_source' },
    { name: '设备型号', value: 'device_type' },
    { name: '设备系统版本', value: 'os_version' },
    { name: '成本类型', value: 'af_cost_model' },
    { name: 'CPI', value: 'af_cost_value' },
    { name: 'APP版本', value: 'app_version' },
    { name: '广告', value: 'af_ad' },
    { name: '运营商', value: 'carrier' },
  ],
};
